// @ts-nocheck
import * as __fd_glob_128 from "../content/docs/ox_lib/Points/Lua/Client.mdx?collection=docs"
import * as __fd_glob_127 from "../content/docs/ox_inventory/Functions/Server/index.mdx?collection=docs"
import * as __fd_glob_126 from "../content/docs/ox_inventory/Functions/Server/Hooks.mdx?collection=docs"
import * as __fd_glob_125 from "../content/docs/ox_lib/Interface/Client/textui.mdx?collection=docs"
import * as __fd_glob_124 from "../content/docs/ox_lib/Interface/Client/skillcheck.mdx?collection=docs"
import * as __fd_glob_123 from "../content/docs/ox_lib/Interface/Client/radial.mdx?collection=docs"
import * as __fd_glob_122 from "../content/docs/ox_lib/Interface/Client/progress.mdx?collection=docs"
import * as __fd_glob_121 from "../content/docs/ox_lib/Interface/Client/notify.mdx?collection=docs"
import * as __fd_glob_120 from "../content/docs/ox_lib/Interface/Client/menu.mdx?collection=docs"
import * as __fd_glob_119 from "../content/docs/ox_lib/Interface/Client/input.mdx?collection=docs"
import * as __fd_glob_118 from "../content/docs/ox_lib/Interface/Client/index.mdx?collection=docs"
import * as __fd_glob_117 from "../content/docs/ox_lib/Interface/Client/context.mdx?collection=docs"
import * as __fd_glob_116 from "../content/docs/ox_lib/Interface/Client/clipboard.mdx?collection=docs"
import * as __fd_glob_115 from "../content/docs/ox_lib/Interface/Client/alert.mdx?collection=docs"
import * as __fd_glob_114 from "../content/docs/ox_lib/Points/JavaScript/Client.mdx?collection=docs"
import * as __fd_glob_113 from "../content/docs/ox_lib/GetNearbyVehicles/Lua/Shared.mdx?collection=docs"
import * as __fd_glob_112 from "../content/docs/ox_lib/GetNearbyVehicles/JavaScript/Shared.mdx?collection=docs"
import * as __fd_glob_111 from "../content/docs/ox_lib/Dui/Lua/Client.mdx?collection=docs"
import * as __fd_glob_110 from "../content/docs/ox_lib/Dui/Javascript/Client.mdx?collection=docs"
import * as __fd_glob_109 from "../content/docs/ox_lib/Callback/Lua/Server.mdx?collection=docs"
import * as __fd_glob_108 from "../content/docs/ox_lib/Callback/Lua/Client.mdx?collection=docs"
import * as __fd_glob_107 from "../content/docs/ox_lib/Callback/JavaScript/Server.mdx?collection=docs"
import * as __fd_glob_106 from "../content/docs/ox_lib/Callback/JavaScript/Client.mdx?collection=docs"
import * as __fd_glob_105 from "../content/docs/ox_core/Classes/Client/OxPlayer.mdx?collection=docs"
import * as __fd_glob_104 from "../content/docs/ox_core/Classes/Server/OxVehicle.mdx?collection=docs"
import * as __fd_glob_103 from "../content/docs/ox_core/Classes/Server/OxPlayer.mdx?collection=docs"
import * as __fd_glob_102 from "../content/docs/ox_core/Classes/Server/OxAccount.mdx?collection=docs"
import * as __fd_glob_101 from "../content/docs/ox_doorlock/Server/functions/index.mdx?collection=docs"
import * as __fd_glob_100 from "../content/docs/ox_doorlock/Server/functions/Hooks.mdx?collection=docs"
import * as __fd_glob_99 from "../content/docs/ox_inventory/Events/Server.mdx?collection=docs"
import * as __fd_glob_98 from "../content/docs/ox_inventory/Events/Client.mdx?collection=docs"
import * as __fd_glob_97 from "../content/docs/ox_target/Functions/Client.mdx?collection=docs"
import * as __fd_glob_96 from "../content/docs/ox_inventory/Guides/stashes.mdx?collection=docs"
import * as __fd_glob_95 from "../content/docs/ox_inventory/Guides/shops.mdx?collection=docs"
import * as __fd_glob_94 from "../content/docs/ox_inventory/Guides/metadata.mdx?collection=docs"
import * as __fd_glob_93 from "../content/docs/ox_inventory/Guides/creatingItems.mdx?collection=docs"
import * as __fd_glob_92 from "../content/docs/ox_inventory/Guides/crafting.mdx?collection=docs"
import * as __fd_glob_91 from "../content/docs/ox_inventory/Functions/Client.mdx?collection=docs"
import * as __fd_glob_90 from "../content/docs/ox_inventory/Frameworks/qbx.mdx?collection=docs"
import * as __fd_glob_89 from "../content/docs/ox_inventory/Frameworks/esx.mdx?collection=docs"
import * as __fd_glob_88 from "../content/docs/ox_lib/Zones/Shared.mdx?collection=docs"
import * as __fd_glob_87 from "../content/docs/ox_lib/WaitFor/Shared.mdx?collection=docs"
import * as __fd_glob_86 from "../content/docs/ox_lib/Version/Shared.mdx?collection=docs"
import * as __fd_glob_85 from "../content/docs/ox_lib/Version/Server.mdx?collection=docs"
import * as __fd_glob_84 from "../content/docs/ox_lib/VehicleProperties/Client.mdx?collection=docs"
import * as __fd_glob_83 from "../content/docs/ox_lib/Table/Shared.mdx?collection=docs"
import * as __fd_glob_82 from "../content/docs/ox_lib/Timer/Shared.mdx?collection=docs"
import * as __fd_glob_81 from "../content/docs/ox_lib/String/Shared.mdx?collection=docs"
import * as __fd_glob_80 from "../content/docs/ox_lib/Streaming/Client.mdx?collection=docs"
import * as __fd_glob_79 from "../content/docs/ox_lib/Raycast/Client.mdx?collection=docs"
import * as __fd_glob_78 from "../content/docs/ox_lib/Selector/Shared.mdx?collection=docs"
import * as __fd_glob_77 from "../content/docs/ox_lib/Scaleform/Client.mdx?collection=docs"
import * as __fd_glob_76 from "../content/docs/ox_lib/Require/Shared.mdx?collection=docs"
import * as __fd_glob_75 from "../content/docs/ox_lib/Print/Shared.mdx?collection=docs"
import * as __fd_glob_74 from "../content/docs/ox_lib/Math/Shared.mdx?collection=docs"
import * as __fd_glob_73 from "../content/docs/ox_lib/PlayAnim/Client.mdx?collection=docs"
import * as __fd_glob_72 from "../content/docs/ox_lib/Marker/Client.mdx?collection=docs"
import * as __fd_glob_71 from "../content/docs/ox_lib/Logger/Server.mdx?collection=docs"
import * as __fd_glob_70 from "../content/docs/ox_lib/Locale/Shared.mdx?collection=docs"
import * as __fd_glob_69 from "../content/docs/ox_lib/Grid/Shared.mdx?collection=docs"
import * as __fd_glob_68 from "../content/docs/ox_lib/GetNearbyPlayers/Shared.mdx?collection=docs"
import * as __fd_glob_67 from "../content/docs/ox_lib/GetNearbyPeds/Shared.mdx?collection=docs"
import * as __fd_glob_66 from "../content/docs/ox_lib/GetNearbyObjects/Shared.mdx?collection=docs"
import * as __fd_glob_65 from "../content/docs/ox_lib/GetFilesInDirectory/Server.mdx?collection=docs"
import * as __fd_glob_64 from "../content/docs/ox_lib/GetClosestVehicle/Shared.mdx?collection=docs"
import * as __fd_glob_63 from "../content/docs/ox_lib/GetClosestPlayer/Server.mdx?collection=docs"
import * as __fd_glob_62 from "../content/docs/ox_lib/GetClosestPlayer/Client.mdx?collection=docs"
import * as __fd_glob_61 from "../content/docs/ox_lib/GetClosestPed/Shared.mdx?collection=docs"
import * as __fd_glob_60 from "../content/docs/ox_lib/GetClosestObject/Shared.mdx?collection=docs"
import * as __fd_glob_59 from "../content/docs/ox_lib/DisableControls/Client.mdx?collection=docs"
import * as __fd_glob_58 from "../content/docs/ox_lib/Cron/Server.mdx?collection=docs"
import * as __fd_glob_57 from "../content/docs/ox_lib/Class/Shared.mdx?collection=docs"
import * as __fd_glob_56 from "../content/docs/ox_lib/Cache/Shared.mdx?collection=docs"
import * as __fd_glob_55 from "../content/docs/ox_lib/Cache/Client.mdx?collection=docs"
import * as __fd_glob_54 from "../content/docs/ox_lib/Array/Shared.mdx?collection=docs"
import * as __fd_glob_53 from "../content/docs/ox_lib/ACL/Server.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/ox_lib/AddKeybind/Client.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/ox_lib/AddCommand/Server.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/ox_core/Functions/server.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/ox_core/Functions/common.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/ox_core/Events/server.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/ox_core/Events/client.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/ox_doorlock/Client/functions.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/ox_fuel/Server/functions.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/oxmysql/Functions/update.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/oxmysql/Functions/transaction.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/oxmysql/Functions/single.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/oxmysql/Functions/scalar.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/oxmysql/Functions/rawExecute.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/oxmysql/Functions/query.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/oxmysql/Functions/prepare.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/oxmysql/Functions/insert.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/ox_fuel/Client/functions.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/ox_doorlock/Server/events.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/resources/templates.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/resources/tebex-creators.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/resources/prism-host.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/resources/index.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/resources/fivemanage.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/ox_target/TargetOptions.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/ox_target/index.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/ox_inventory/issues.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/ox_inventory/index.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/ox_lib/Vehicle.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/ox_lib/Prop.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/ox_lib/Player.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/ox_lib/Ped.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/ox_lib/index.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/ox_lib/Hooks.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/ox_lib/GameEntity.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/ox_core/States.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/ox_core/index.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/ox_fuel/Shared.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/ox_fuel/index.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/ox_doorlock/settings.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/ox_doorlock/index.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/oxmysql/ui.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/oxmysql/placeholders.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/oxmysql/index.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/oxmysql/benchmark.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/guides/nodejs.mdx?collection=docs"
import * as __fd_glob_7 from "../content/docs/guides/lua-types.mdx?collection=docs"
import * as __fd_glob_6 from "../content/docs/guides/index.mdx?collection=docs"
import * as __fd_glob_5 from "../content/docs/guides/git.mdx?collection=docs"
import * as __fd_glob_4 from "../content/docs/guides/bun.mdx?collection=docs"
import * as __fd_glob_3 from "../content/docs/index.mdx?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/ox_lib/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/guides/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
} & {
  DocData: {
    docs: {
      /**
       * Last modified date of document file, obtained from version control.
       *
       */
      lastModified?: Date;
    },
  }
}>({"doc":{"passthroughs":["extractedReferences","lastModified"]}});

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_0, "guides/meta.json": __fd_glob_1, "ox_lib/meta.json": __fd_glob_2, }, {"index.mdx": __fd_glob_3, "guides/bun.mdx": __fd_glob_4, "guides/git.mdx": __fd_glob_5, "guides/index.mdx": __fd_glob_6, "guides/lua-types.mdx": __fd_glob_7, "guides/nodejs.mdx": __fd_glob_8, "oxmysql/benchmark.mdx": __fd_glob_9, "oxmysql/index.mdx": __fd_glob_10, "oxmysql/placeholders.mdx": __fd_glob_11, "oxmysql/ui.mdx": __fd_glob_12, "ox_doorlock/index.mdx": __fd_glob_13, "ox_doorlock/settings.mdx": __fd_glob_14, "ox_fuel/index.mdx": __fd_glob_15, "ox_fuel/Shared.mdx": __fd_glob_16, "ox_core/index.mdx": __fd_glob_17, "ox_core/States.mdx": __fd_glob_18, "ox_lib/GameEntity.mdx": __fd_glob_19, "ox_lib/Hooks.mdx": __fd_glob_20, "ox_lib/index.mdx": __fd_glob_21, "ox_lib/Ped.mdx": __fd_glob_22, "ox_lib/Player.mdx": __fd_glob_23, "ox_lib/Prop.mdx": __fd_glob_24, "ox_lib/Vehicle.mdx": __fd_glob_25, "ox_inventory/index.mdx": __fd_glob_26, "ox_inventory/issues.mdx": __fd_glob_27, "ox_target/index.mdx": __fd_glob_28, "ox_target/TargetOptions.mdx": __fd_glob_29, "resources/fivemanage.mdx": __fd_glob_30, "resources/index.mdx": __fd_glob_31, "resources/prism-host.mdx": __fd_glob_32, "resources/tebex-creators.mdx": __fd_glob_33, "resources/templates.mdx": __fd_glob_34, "ox_doorlock/Server/events.mdx": __fd_glob_35, "ox_fuel/Client/functions.mdx": __fd_glob_36, "oxmysql/Functions/insert.mdx": __fd_glob_37, "oxmysql/Functions/prepare.mdx": __fd_glob_38, "oxmysql/Functions/query.mdx": __fd_glob_39, "oxmysql/Functions/rawExecute.mdx": __fd_glob_40, "oxmysql/Functions/scalar.mdx": __fd_glob_41, "oxmysql/Functions/single.mdx": __fd_glob_42, "oxmysql/Functions/transaction.mdx": __fd_glob_43, "oxmysql/Functions/update.mdx": __fd_glob_44, "ox_fuel/Server/functions.mdx": __fd_glob_45, "ox_doorlock/Client/functions.mdx": __fd_glob_46, "ox_core/Events/client.mdx": __fd_glob_47, "ox_core/Events/server.mdx": __fd_glob_48, "ox_core/Functions/common.mdx": __fd_glob_49, "ox_core/Functions/server.mdx": __fd_glob_50, "ox_lib/AddCommand/Server.mdx": __fd_glob_51, "ox_lib/AddKeybind/Client.mdx": __fd_glob_52, "ox_lib/ACL/Server.mdx": __fd_glob_53, "ox_lib/Array/Shared.mdx": __fd_glob_54, "ox_lib/Cache/Client.mdx": __fd_glob_55, "ox_lib/Cache/Shared.mdx": __fd_glob_56, "ox_lib/Class/Shared.mdx": __fd_glob_57, "ox_lib/Cron/Server.mdx": __fd_glob_58, "ox_lib/DisableControls/Client.mdx": __fd_glob_59, "ox_lib/GetClosestObject/Shared.mdx": __fd_glob_60, "ox_lib/GetClosestPed/Shared.mdx": __fd_glob_61, "ox_lib/GetClosestPlayer/Client.mdx": __fd_glob_62, "ox_lib/GetClosestPlayer/Server.mdx": __fd_glob_63, "ox_lib/GetClosestVehicle/Shared.mdx": __fd_glob_64, "ox_lib/GetFilesInDirectory/Server.mdx": __fd_glob_65, "ox_lib/GetNearbyObjects/Shared.mdx": __fd_glob_66, "ox_lib/GetNearbyPeds/Shared.mdx": __fd_glob_67, "ox_lib/GetNearbyPlayers/Shared.mdx": __fd_glob_68, "ox_lib/Grid/Shared.mdx": __fd_glob_69, "ox_lib/Locale/Shared.mdx": __fd_glob_70, "ox_lib/Logger/Server.mdx": __fd_glob_71, "ox_lib/Marker/Client.mdx": __fd_glob_72, "ox_lib/PlayAnim/Client.mdx": __fd_glob_73, "ox_lib/Math/Shared.mdx": __fd_glob_74, "ox_lib/Print/Shared.mdx": __fd_glob_75, "ox_lib/Require/Shared.mdx": __fd_glob_76, "ox_lib/Scaleform/Client.mdx": __fd_glob_77, "ox_lib/Selector/Shared.mdx": __fd_glob_78, "ox_lib/Raycast/Client.mdx": __fd_glob_79, "ox_lib/Streaming/Client.mdx": __fd_glob_80, "ox_lib/String/Shared.mdx": __fd_glob_81, "ox_lib/Timer/Shared.mdx": __fd_glob_82, "ox_lib/Table/Shared.mdx": __fd_glob_83, "ox_lib/VehicleProperties/Client.mdx": __fd_glob_84, "ox_lib/Version/Server.mdx": __fd_glob_85, "ox_lib/Version/Shared.mdx": __fd_glob_86, "ox_lib/WaitFor/Shared.mdx": __fd_glob_87, "ox_lib/Zones/Shared.mdx": __fd_glob_88, "ox_inventory/Frameworks/esx.mdx": __fd_glob_89, "ox_inventory/Frameworks/qbx.mdx": __fd_glob_90, "ox_inventory/Functions/Client.mdx": __fd_glob_91, "ox_inventory/Guides/crafting.mdx": __fd_glob_92, "ox_inventory/Guides/creatingItems.mdx": __fd_glob_93, "ox_inventory/Guides/metadata.mdx": __fd_glob_94, "ox_inventory/Guides/shops.mdx": __fd_glob_95, "ox_inventory/Guides/stashes.mdx": __fd_glob_96, "ox_target/Functions/Client.mdx": __fd_glob_97, "ox_inventory/Events/Client.mdx": __fd_glob_98, "ox_inventory/Events/Server.mdx": __fd_glob_99, "ox_doorlock/Server/functions/Hooks.mdx": __fd_glob_100, "ox_doorlock/Server/functions/index.mdx": __fd_glob_101, "ox_core/Classes/Server/OxAccount.mdx": __fd_glob_102, "ox_core/Classes/Server/OxPlayer.mdx": __fd_glob_103, "ox_core/Classes/Server/OxVehicle.mdx": __fd_glob_104, "ox_core/Classes/Client/OxPlayer.mdx": __fd_glob_105, "ox_lib/Callback/JavaScript/Client.mdx": __fd_glob_106, "ox_lib/Callback/JavaScript/Server.mdx": __fd_glob_107, "ox_lib/Callback/Lua/Client.mdx": __fd_glob_108, "ox_lib/Callback/Lua/Server.mdx": __fd_glob_109, "ox_lib/Dui/Javascript/Client.mdx": __fd_glob_110, "ox_lib/Dui/Lua/Client.mdx": __fd_glob_111, "ox_lib/GetNearbyVehicles/JavaScript/Shared.mdx": __fd_glob_112, "ox_lib/GetNearbyVehicles/Lua/Shared.mdx": __fd_glob_113, "ox_lib/Points/JavaScript/Client.mdx": __fd_glob_114, "ox_lib/Interface/Client/alert.mdx": __fd_glob_115, "ox_lib/Interface/Client/clipboard.mdx": __fd_glob_116, "ox_lib/Interface/Client/context.mdx": __fd_glob_117, "ox_lib/Interface/Client/index.mdx": __fd_glob_118, "ox_lib/Interface/Client/input.mdx": __fd_glob_119, "ox_lib/Interface/Client/menu.mdx": __fd_glob_120, "ox_lib/Interface/Client/notify.mdx": __fd_glob_121, "ox_lib/Interface/Client/progress.mdx": __fd_glob_122, "ox_lib/Interface/Client/radial.mdx": __fd_glob_123, "ox_lib/Interface/Client/skillcheck.mdx": __fd_glob_124, "ox_lib/Interface/Client/textui.mdx": __fd_glob_125, "ox_inventory/Functions/Server/Hooks.mdx": __fd_glob_126, "ox_inventory/Functions/Server/index.mdx": __fd_glob_127, "ox_lib/Points/Lua/Client.mdx": __fd_glob_128, });